### PR TITLE
External plugins: Add meshname and meship

### PR DESCRIPTION
**Pull request by marek22k**
see https://github.com/zhoreeq/meshname and https://github.com/zhoreeq/meshname/blob/master/protocol.md

### CODE REVIEW

**Comment by chrisohaver** [comment]
Sorry for the delay in review!  Can you provide a bit more background on what meship and meshname are, with examples of domains and queries/responses? I'm not familiar with these - perhaps other may not be as well.

**Comment by marek22k** [comment]
The protocol specification can be found at https://github.com/zhoreeq/meshname/blob/master/protocol.md. To put it simply, it's a simple way to encode the IPv6 address of the authoritative server and convert it into a domain - so you don't have to rely on a central DNS architecture. When resolving a meshname domain, the authoritative DNS server encoded in the domain is then queried. This also makes subdomains possible. The only disadvantage is that the names look a bit confusing.
So it meets the criteria of "Secure" and "Decentralized" but not of "Freely Selectable" of Zooko's triangle.

**Comment by chrisohaver** [comment]
Thanks.  I meant to say, can you provide a background in the plugin READMEs (meship.md and meshname.ip), so it's easier for others viewing your plugin to know what it does.

**Comment by marek22k** [comment]
I tried to write something about it. If you have an idea how to word it better, I'm open.

**Review by chrisohaver — APPROVED** [review]

**Pull request merged**
