### PR TITLE
CoreDNS in K8s scaling blog

### PR DESCRIPTION
**Pull request by chrisohaver**
This is a blogified summary of the recently merged scaling doc ... https://github.com/coredns/deployment/blob/master/kubernetes/Scaling_CoreDNS.md

### CODE REVIEW

**Comment by chrisohaver** [comment]
@fturib @miekg

**Comment by miekg** [comment]
When do you want to push this out?

**Comment by fturib** [comment]
hum about time ...and date.
@chrisohaver : neither the blog, neither the reference doc are mentioning the version of CoreDNS used for the test. I think it should .. no ?

**Comment by chrisohaver** [comment]
Lets hold off on this one - I realize now that somehow I was using an old/alpha version of kubernetes (1.10 alpha)... so the tests may be invalid.  I should retest.

**Comment by chrisohaver** [comment]
> somehow I was using an old/alpha version of kubernetes (1.10 alpha)...

No, this appears to have been an artifact of how the Kubernetes binaries were built ... I think 1.10-alpha being the base version, then code updated to a current commit and built.  So the actual version used was the current master.

**Comment by fturib** [comment]
@miekg , @chrisohaver : can we plan to merge this blog for the 11/15 ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] CoreDNS in..." ]
>@miekg , @chrisohaver : can we plan to merge this blog for the 11/15 ?

Check.

**Comment by fturib** [comment]
@miekg : can you merge it ? Thanks.

**Comment by miekg** [comment]
Oh yeah..forgot thanks for the ping. Will push this out as soon as I have
some internet connection. (Traveling)

**Pull request merged**
