### PR TITLE
hero, header and footer look-feel improvements

### PR DESCRIPTION
**Pull request by reveurguy**
Signed-off-by: reveurguy <59417546+reveurguy@users.noreply.github.com>
Made initial improvements to the website by making changes in hero section, header and footer. Please provide any feedback or changes. Will make improvements to the rest of the website as well.

Thank you for contributing to CoreDNS' website!

Note:

 *  All text listed in /plugins is a *copied* from
    [https://github.com/coredns/coredns/tree/master/plugin](https://github.com/coredns/coredns/tree/master/plugin).

 *  The release notes are *copied* from
    [https://github.com/coredns/coredns/tree/master/notes](https://github.com/coredns/coredns/tree/master/notes).

Any pull request that updates either of those should be *directed* to the CoreDNS repository:
[https://github.com/coredns/coredns](https://github.com/coredns/coredns) .

### CODE REVIEW

**Comment by chrisohaver** [comment]
Please put a description of the changes you are making in the PR Description.

**Comment by reveurguy** [comment]
I have mentioned the changes.

**Comment by chrisohaver** [comment]
> I have mentioned the changes.

> “Made initial improvements to the website by making changes in hero section, header and footer.”


This is too vague. Please _describe_ the changes.

**Comment by reveurguy** [comment]
Made initial changes to improve the website look and design. 

1. I changed the background of the header, hero section and footer.
2. Improved the navbar look and added twitter, slack and github links as logos.
3. Improved the hero section buttons looks and style, also improved the version-release notes section look.

**Comment by reveurguy** [comment]
@chrisohaver I have made more changes to the homepage. Now it is fully improved. please have a look at it and do provide me any feedback or suggestions.

**Comment by chrisohaver** [comment]
This is a pretty significant re-design ... reviewing a change of this scope isn't my wheelhouse.

Maybe a CNCF resource can help review the proposed new look?

**Comment by chrisohaver** [comment]
On the whole, I prefer the existing cold condensed presentation over the more whimsical proposed design.  This is just my preference.  That said the website isn't made for me; it exists for other people, and I don't know what _their_ preference is.

**Comment by reveurguy** [comment]
We can share the website in the slack channel and ask other maintainers and members for their view. That would help.

**Comment by reveurguy** [comment]
> This is a pretty significant re-design ... reviewing a change of this scope isn't my wheelhouse.
> 
> Maybe a website-designy person from CNCF can help review the proposed new look?
> 

Yes we can do that as well if you want.

**Comment by chrisohaver** [comment]
@bradbeam @chrisohaver @dilyevsky @jameshartig @greenpau @isolus @johnbelamaric @miekg @pmoroney @rajansandeep @stp-ip @superq @yongtang @Tantalor93

Please see this proposed redesign of coredns.io, and provide feedback:

https://deploy-preview-267--coredns.netlify.app

**Review by chrisohaver — CHANGES_REQUESTED** [review]
On the whole, I prefer the existing design over the proposed design.

**Comment by Tantalor93** [comment]
On my phone it is quite a regression in a UX 
F85DD09C-FE1D-4036-A4C2-C792FCDEC3F4 I cant even see the header

**Comment by chrisohaver** [comment]
> On my phone it is quite a regression in a UX

Thanks for taking a look! I noticed the mobile dispaly issues too.  Although I think we should make sure there is a consensus to move forward with the proposed look and feel before spending time ironing out bugs in the new design.

**Comment by reveurguy** [comment]
These are the initial changes only, so i made it w.r.t to laptop size only, haven't made it responsive, that's why it will not look good on mobile, would be visible perfectly on laptop.

**Comment by bradbeam** [comment]
> On the whole, I prefer the existing cold condensed presentation over the more whimsical proposed design. This is just my preference.
> On the whole, I prefer the existing design over the proposed design.

I fall into this bucket as well. Some general comments/opinions, 
- I find the gradient header to be very busy and sometimes hides/obscures the text/links ( ex, on the plugins page, the text under `Plugins`; when hovering over the `Documenting Plugins` link, the box nearly disappears )
- The shadow(?) under the landing page topics made me think I had the text selected; I find it a bit distracting
- I do like the CNCF graduation banner

**Comment by Isolus** [comment]
> On the whole, I prefer the existing cold condensed presentation over the more whimsical proposed design. This is just my preference. That said the website isn't made for me (a CoreDNS maintainer)

I'll go along with that as well.

Also, I'm not sure what problem the new design is supposed to solve. Functionally it seems to be similar.  And compared to other sites that have a design that is deemed modern, the old design seems more modern to me than the proposal.

**Comment by dilyevsky** [comment]
> Also, I'm not sure what problem the new design is supposed to solve

**Comment by reveurguy** [comment]
if required I can make the changes suggested, these were only the initial changes so most of them were on the landing page itself, that's why on other pages there would be some issues.
my suggestion and changes were just to make the site look visually better, it doesn't solve any major problem.
if you would like to remain with the current site, i'll close this PR, that's no issue.

**Comment by reveurguy** [comment]
Screenshot 2022-07-21 at 8 09 45 AM

Screenshot 2022-07-21 at 8 10 07 AM

**Comment by Tantalor93** [comment]
I think it seems that the general agreement is to keep the UI of the site as it is, so I think we can close this @reveurguy ? But thanks for the time you spent on this overhaul. Do you agree with closing this PR and keep the site as it is? @chrisohaver @dilyevsky @bradbeam

**Pull request closed without merging**
