### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by dmyerscough**
Spotted this little typo while reading the docs, so I thought I would be the good samaritan and create a pull request ;)

### CODE REVIEW

**Comment by miekg** [comment]
Oh wait, we copy these from coredns' source. Should be in https://github.com/coredns/coredns/blob/master/plugin/health/README.md as well (yes it is)

**Comment by dmyerscough** [comment]
Ill create a PR there too.

**Comment by miekg** [comment]
I'll add a small header under these files highlighting that fact.

**Comment by dmyerscough** [comment]
:+1:

**Pull request merged**
