### PR TITLE
 Auto build and deploy via Netlify

### PR DESCRIPTION
**Pull request by stp-ip**
This adds all remaining configuration to auto build and deploy
via Netlify. In addition to deploying master it also enables PR
review deploys.

It builds up on #178, but happy to rebase after #178 is merged.

### CODE REVIEW

**Comment by miekg** [comment]
is still also needed? (I'm just merging)

**Comment by stp-ip** [comment]
Will rebase and then can merge in. This is the netlify part. So auto syncing should already work, but wanted to separate the syncing from the netlify part.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io]  Auto buil..." ]
>Will rebase and then can merge in. This is the netlify part. So auto syncing should already work, but wanted to separate the syncing from the netlify part.

check.

And tls certs and the like is done by netifly I presume? Currenltly is doesn't.

beta.coredns.io point to netifly btw

**Comment by stp-ip** [comment]
Pushed and ready to merge.

Yes TLS is done via let's encrypt once DNS is switched.

Will enable TLS for beta.coredns.io and check again on the netlify side.

**Comment by stp-ip** [comment]
TLS provisioned for beta.coredns.io \o/

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io]  Auto buil..." ]
>TLS provisioned for beta.coredns.io \o/

woot

**Pull request merged**
