### PR TITLE
Autopath

### PR DESCRIPTION
**Pull request by miekg**

### CODE REVIEW

**Comment by miekg** [comment]
@chrisohaver should we push these out? Or just one first?

**Comment by chrisohaver** [comment]
Just the first one I think, then the 2nd one later.

Does that mean I need to split the PR?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] Autopath (..." ]
>Just the first one I think, then the 2nd one later.
>
>Does that mean I need to split the PR?

No, you put 'draft = "yes"' in the header, it won't display that way. Later we 
can just change the date and remove 'draft'.

**Comment by chrisohaver** [comment]
@miekg , @johnbelamaric  ... Not sure if I can actually modify this PR anymore ...  It's no longer owned by me...

Should we just post both blogs at the same time to make things easier?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] Autopath (..." ]
>@miekg , @johnbelamaric  ... Not sure if I can actually modify this PR anymore ...  It's no longer owned by me...

that's me when I moved all this. This clone this repo, get the branch and start 
a new PR? (that's what I did at least).

>Should we just post both blogs at the same time to make things easier?

Works for me as well. These are ready to go?

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
OK - i'll re-create a PR and give it another once-over.

**Comment by chrisohaver** [comment]
I think we should wait on this until the k8s code base is more stable. Lots of fixes/changes going in now. Perhaps defer these to blog post 1.0.0. release, updating it if needed.  Thoughts?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] Autopath (..." ]
>I think we should wait on this until the k8s code base is more stable. Lots of fixes/changes going in now. Perhaps defer these to blog post 1.0.0. release, updating it if needed.  Thoughts?

fair enough, although I still think it would be nice to document this feature...

**Pull request closed without merging**
