### PR TITLE
fix broken links for lighthouse plugin

### PR DESCRIPTION
**Pull request by mariuskimmina**
Signed-off-by: Marius Kimmina <mar.kimmina@gmail.com>

Noticed 404 responses from the lighthouse plugin, apparently the repo structure has changed.

### CODE REVIEW

**Comment by mariuskimmina** [comment]
Also apparently the image used for the build in netlify needs to be updated. That doesn't appear to be part of any configuration in the repo so I can't do that.

Netlify output:
```
The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
```

**Comment by chrisohaver** [comment]
https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

Apparently needs to be done in netlify ui.

I don’t know who has access to this.

**Comment by chrisohaver** [comment]
Thinking maybe we should move the website to GitHub pages on coredns/coredns?

**Comment by mariuskimmina** [comment]
+1 for Github Pages

**Pull request merged**
