### PR TITLE
Add dns64 plugin

### PR DESCRIPTION
**Pull request by serverwentdown**

### CODE REVIEW

**Comment by fturib** [comment]
Thank you for the update on authoritative/recursive modes !

Should we make clear that, as first version, only simple AAAA synthetization is performed. 
I mean : no PTR process, CNAME/DNAME follow-up, no DNSSEC, etc ... ?

**Comment by serverwentdown** [comment]
I added it as a TODO

**Comment by fturib** [comment]
I am adding here some extra comment on this plugin, although that is already merged.

**is the "upstream" parameter useful ?**

Why not have the DNS64 re-queried with A Type, the same way it queried the AAAA, and let the configuration decide of both goes to upstream (via proxy plugin) or locally (via another other resolving plugin) ?

That would required ability to "re-query" the stream with same query but type modified.

Similar call is done in the "autopath" plugin (see autpopath.go, line 110).
Maybe it requires to have the logic (and the second call) in ServeDNS instead of current implementation in ResponseWriter ... 

Doing so, you let the configuration decide the mode (and avoid the second marshaling )

**Sample for configuration**

recursive mode, we could have:

```
dns64
proxy . 8.8.8.8
```

and for authoritative mode we would have 👍 

```
dns64
file whatever.db
etc ...
```
 

Would it work ?

**Comment by serverwentdown** [comment]
While achieving the above, I would end up implementing the plugin stack to perform an internal query, which instead should be part of the core, exposed for use by plugins (in my opinion). When I get some free time I'll try it out within my plugin using something akin to `autopath`.

**Pull request merged**
