### PR TITLE
Add `finalize` external plugin

### PR DESCRIPTION
**Pull request by tmeckel**
This PR adds the `finalize`external plugin.

`*finalize*` - resolves CNAMEs to their IP address.

https://github.com/tmeckel/coredns-finalizer/blob/master/README.md

### CODE REVIEW

**Comment by chrisohaver** [comment]
Thanks!

One thing that is not clear in the README  is that this does not simply resolve CNAMEs ... it also "collapses" them into a single A/AAAA result.  That approach is problematic because RR names in the answer will not match the query name. Some resolvers will reject the response with a name mismatch error.  The "DNS way" to resolve CNAMEs is to amend the response with the looked-up records instead of replacing the CNAMEs. Resolves receive the CNAME and the target records in the answer.

If removing the CNAMEs is required for some special reason, then the answer names in the response should be made to match the query name before writing it to the client.  I think removing the CNAMEs probably isn't what you want to do though.  If it is, you should describe that scenario in the README. 

Another issue is that CNAMEs can point to a target name that has more than one RR for a given type. e.g. two A records.  This plugin will only return one, which is an incomplete answer.

One minor comment: Implementing ready to always return true isn't needed - it's better to just not implement the interface.  This just creates more work for the ready plugin (albeit a very small amount of work).

**Comment by tmeckel** [comment]
@chrisohaver thanks for the review. Let me begin with the easy part 😀 

> One minor comment: Implementing ready to always return true isn't needed - it's better to just not implement the interface. This just creates more work for the ready plugin (albeit a very small amount of work).

I removed the `ready.go` implementation as you purposed.

> One thing that is not clear in the README is that this does not simply resolve CNAMEs ... it also "collapses" them into a single A/AAAA result. That approach is problematic because RR names in the answer will not match the query name. Some resolvers will reject the response with a name mismatch error. The "DNS way" to resolve CNAMEs is to amend the response with the looked-up records instead of replacing the CNAMEs. Resolvers receive the CNAME and the target records in the answer.
> 
> If removing the CNAMEs is required for some special reason, then the answer names in the response should be made to match the query name before writing it to the client. I think removing the CNAMEs probably isn't what you want to do though. If it is, you should describe that scenario in the README.
> 

I changed the code in a way that all (intermediate) CNAMEs are copied over to the final answer, namely in the sequence how they are processed by the plugin. The following picture shows the result if a CNAME got resolved into it's A RR. 

image

The sample implements the strategy Azure imposes on DNS when `private links`come into play.

image

[Azure Private Endpoint DNS configuration](https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns)
[Virtual network and on-premises workloads using a DNS forwarder](https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns#virtual-network-and-on-premises-workloads-using-a-dns-forwarder)

The following `Corefile` is used:

image

> Another issue is that CNAMEs can point to a target name that has more than one RR for a given type. e.g. two A records. This plugin will only return one, which is an incomplete answer.
> 

All target RRs of a CNAME are now copied over to the final answer:

image

While implementing and testing the new code based on your suggestions and remarks, I discovered that it is impossible to send any DNS queries via the `forward` plugin when it gets called by `upstream.Lookup`, because the implementation of `forward` is using a cache and the cache will always return a connection that always returns `EOF` while writing to it. 

I fiddled around with the code, but never get it to work, i.e. sending out a new query via the `forward` plugin when the `finalize` plugin used the `upstream.Lookup` function to query for a DNS answer for a CNAME.

Am I using the `upstream.Lookup` function wrong? Or is it simply because I'm calling `upstream.Lookup` from a `response modifier` ? I discovered no issues with other plugins like the `azure` plugin or the `hosts` plugin, which is used in the `Corefile` shown above.

**Comment by tmeckel** [comment]
One addition to my statements about the problem with the `forward` plugin: I created an another version of my plugin which uses `nonwriter` that _'...implements a dns.ResponseWriter that never writes, but captures the dns.Msg being written.'_ By utilizing `nonwriter` all code can run inside `ServeDNS` and thus spares a `response modifier`. (I copied the strategy from the [`alternate` plugin](https://github.com/coredns/alternate). 

Sadly enough I didn't have much luck: I receive the same `EOF`error from the `forward` plugin, when it got called via `upstream.Lookup`. So from my point of view the issue isn't related with the `response modifier` what I initially thought.

**Comment by chrisohaver** [comment]
> I created an another version of my plugin which uses `nonwriter`.

I suspect that approach is a little bit cleaner (less code).

It's not immediately obvious to me why things aren't working.  Maybe the locally scoped context modification is part of it?
An alternate approach would be to allow the plugin to do a single CNAME look up in each recursion, instead of doing all the lookups at the end. In that way, you don't need to add a key to the context (or loop CNAME lookups). I think it would be equally performant.

While reading over the code again, I found another issue: If the answer from the plugin already contains the CNAME target, finalize look it up again, and add a duplicate to the answer.

**Pull request merged**
